### PR TITLE
Allow non tls server

### PR DESCRIPTION
**Pull request by dkjer**
This PR allows running the auth server as http:// instead of https://.  Our use-case is that we prefer to configure https at the ELB level, not at the internal node level.

[Review on Reviewable](https://reviewable.io/reviews/cesanta/docker_auth/25)

### CODE REVIEW

**Comment by rojer** [comment]
i considered doing that, but then thought that since token signing cert is required anyway, it won't be of any benefit. hence the ability to use one cert for both signing and TLS.
is there any reason why that doesn't work for you?

**Comment by rojer** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[auth_server/main.go, line 50 \[r1\]](https://reviewable.io:443/reviews/cesanta/docker_auth/25#-JxrQRRMUGJxEGVTnE95)** ([raw file](https://github.com/cesanta/docker_auth/blob/ad4b3fda8fec6f8090a1dedf52b1d2d6bdef1242/auth_server/main.go#L50)):</sup>
same here: have it load the the cert/key if any of them is specified, which will fail if one isn't, but that's fine.

---

<sup>**[auth_server/server/config.go, line 125 \[r1\]](https://reviewable.io:443/reviews/cesanta/docker_auth/25#-JxrQMNIpYPYvQ33OtLX)** ([raw file](https://github.com/cesanta/docker_auth/blob/ad4b3fda8fec6f8090a1dedf52b1d2d6bdef1242/auth_server/server/config.go#L125)):</sup>
make a case where only one is specified an error, as it doesn't make sense to specify only cert or only key.

---

<sup>**[auth_server/server/config.go, line 138 \[r1\]](https://reviewable.io:443/reviews/cesanta/docker_auth/25#-JxrPVg6Oxm4xy9VCZce)** ([raw file](https://github.com/cesanta/docker_auth/blob/ad4b3fda8fec6f8090a1dedf52b1d2d6bdef1242/auth_server/server/config.go#L138)):</sup>
actually, both are required

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/docker_auth/25)

**Comment by dkjer** [comment]
@rojer Using one cert for both signing and TLS does work, and we may end up doing that for production.  However we prefer to decouple that for now, at least in our dev environment.

**Comment by rojer** [comment]
@dkjer: still not sure i understand the reasoning, but will merge once comments are addressed.

**Comment by dkjer** [comment]
Rebased with comments addressed

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/docker_auth/25)

**Comment by rojer** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/docker_auth/25)

**Comment by rojer** [comment]
built and pushed to :latest

**Comment by dkjer** [comment]
Thanks @rojer !

**Comment by djenriquez** [comment]
@rojer, @dkjer I see that this has been merged, but how does one set up the registry config to use this? The registry config hard requries a rootcertbundle, but if TLS is disabled?

I'm also looking at doing TLS termination on the ELB rather than in the auth server.

Could you provide examples of both the registry config and the auth server config?

Thanks!!!

**Pull request merged**
