### PR TITLE
GitHub authn

### PR DESCRIPTION
**Pull request by raphink**
This is a new PR like #115, but squashed.

---
This change is [Reviewable](https://reviewable.io/reviews/cesanta/docker_auth/119)

### CODE REVIEW

**Comment by raphink** [comment]
@rojer squashed down to 11 commits already:

* 1 commit to add GitHub authn
* 1 commit for TokenDB
* 3 "typo" commits at the end

the rest is commits I'm having a hard time squashing because they depend on TokenDB. I'll try to see how I can simplify a bit more.

**Comment by rojer** [comment]
sorry for being pedantic, but this needs to be squashed more. for those who come later, back and forth about location of documentation or revalidate vs retrieve is really just noise. ideally, this should be three commits: pulling out TokenDB interface, implementing GH provider, fixing typos in old stuff. or two commits - adding new stuff and fixing typos in old stuff. or just one will do as well, just as long as it's not this noisy.

**Comment by rojer** [comment]
oh, something just changed on my screen. are you squashing? ok, let me know when you're done.

**Comment by raphink** [comment]
OK, I'm down to 3 commits now:

* Add GitHub + TokenDB (because splitting the two was just a nightmare)
* Fix a bug (nil in logs)
* Fix typos

**Comment by rojer** [comment]
great, thanks!

**Comment by raphink** [comment]
Thanks for merging. Now to move to #118. If you want to comment and bring in ideas, I'll get coding on it soon.

**Comment by rojer** [comment]
just noticed that organization parameter is not documented in reference.yml, please send a followup.

**Comment by raphink** [comment]
@rojer see #120

**Pull request merged**
