### PR TITLE
Update helm chart

### PR DESCRIPTION
**Pull request by pfisterer**
Thank you @duyanghao for contributing the helm charts for docker_auth. It took me a while to deploy docker_auth together with docker-registry in order to deploy a private registry in Kubernetes.

This PR complements the great work of @duyanghao by 
- optionally deploying an instance of [docker-registry](https://github.com/helm/charts/tree/master/stable/docker-registry), which will be configured to work together with docker_auth. This uses a file called `requirements.yaml` to pull the dependency in.
- update the ingress to function correctly.

Please be aware that this requires further work on the repository which I cannot add in this pull request. These steps are documented in README.md. This will allow this chart to be available on [helm hub](https://hub.helm.sh/).

Please also note that for this chart to be usable, this [PR 17604](https://github.com/helm/charts/pull/17604) needs to be accepted first. So we have some time to perform these steps.

### CODE REVIEW

**Comment by rojer** [comment]
@carsonoid @duyanghao, does this make sense to you?

**Comment by carsonoid** [comment]
@rojer lgtm.

The `/docs` change mentioned by @pfisterer is the only disruptive thing here, but moving those docs and generating github page for the helm chart is not a requirement and should not prevent this merge.

**Comment by duyanghao** [comment]
@carsonoid @pfisterer @rojer As I understand it, `docker_auth` is only a `Docker Registry 2 authentication server` and does it well. I don't think it is necessary to merge [docker distribution](https://github.com/docker/distribution) into it as this will make this chart complex and hard-to-maintain.
Finally, I want to say that it is more common to deploy a enterprise-class docker hub(such as [harbor](https://github.com/goharbor/harbor)) instead of a native `docker distribution`, and this pr will become redundant in this case.

**Comment by pfisterer** [comment]
Hello @duyanghao,
Thank you for the comments. I think you are right reg. docker vs. harbor. However, the integration with docker registry is optional (cf. requirements.yaml `condition` setting below). It is only activated when `registry.enabled`is true. And I had quite some trouble to connect the two. So I think there is an inherent benefit to connect them automatically via this helm chart. 

I think maintaining this as part of this project is beneficial for consistency reasons (and only costs a few lines of optional code). However, as mentioned in the other PR, I can also maintain this helm chart separately.

So, I'm fine with both options @carsonoid  @rojer.

requirements.yaml:

```yaml 
dependencies:
- name: docker-registry
  version: ^1.8.3
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: registry.enabled
  import-values:
    - child: configData
      parent: registry.configData
```

**Comment by pfisterer** [comment]
Ok, probably https://github.com/helm/charts/commit/97a822fabd0cc1bd506e8cea81010d0e0176d93d fixes this issue as well. I will check and then maybe provide updated docs.

**Comment by pfisterer** [comment]
@carsonoid @rojer: any updates on this? 

In the meantime, I've updated the chart for Helm v3 and I've provided a helm repo until your repo potentially could become one. So users can now do the following:

```bash
# Add the repo
helm repo add pfisterer-knox https://pfisterer.github.io/docker_auth/
helm repo update

# Install everything
helm dependency update
helm install --name=docker-auth ./docker_auth
```

**Comment by rojer** [comment]
i know nothing about this stuff, but if @carsonoid is ok, i can merge.

**Comment by pfisterer** [comment]
Updated to a working example that uses the [extra volume mounts](https://github.com/helm/charts/commit/97a822fabd0cc1bd506e8cea81010d0e0176d93d) feature of the [docker-registry](https://github.com/helm/charts/tree/master/stable/docker-registry) chart. 

This PR now provides a working solution to run docker_auth with a docker-registry deployment. Documentation is available here: <https://github.com/pfisterer/docker_auth/tree/master/chart/docker-auth>. I'm also providing a helm repo on github there.

**Comment by techknowlogick** [comment]
@pfisterer Thanks for this PR. I'm happy to approve it, however could you make a few minor changes first:

1. Change references from your GH pages URLs to cesantas (GH pages will be configured once this is merged)
2. Remove dep on docker registry chart from helm-stable as stable is now deprecated and will be removed (I think the date is Nov 1). This can be added in a later PR once docker registry chart is adopted by Docker (or some other maintainer)
3. Resolve conflict with README.md

**Comment by techknowlogick** [comment]
@pfisterer I've just sent a PR with the above suggestions

**Comment by techknowlogick** [comment]
@pfisterer I've just sent a PR to your repo with the above changes, it can be found here: https://github.com/pfisterer/docker_auth/pull/1

**Comment by techknowlogick** [comment]
This can now be closed.

**Pull request closed without merging**
