### PR TITLE
Mongo authn

### PR DESCRIPTION
**Pull request by carsonoid**
I've expanded the MongoDB support to include a collection for authentication.  This includes a refactor of mgo sessions and the associated structs to a separate package. I've also implemented the Copy->Close flow for sessions as recommended in the mgo docs.

[Review on Reviewable](https://reviewable.io/reviews/cesanta/docker_auth/55)

### CODE REVIEW

**Comment by rojer** [comment]
seems reasonable, just a couple minor comments

also, please squash all the commits into one

---

Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[auth_server/authn/mongo_auth.go, line 52 \[r1\]](https://reviewable.io:443/reviews/cesanta/docker_auth/55#-K5NG5zRp4cvNUuX26BQ:-K5NG5zRp4cvNUuX26BR:2066332879) ([raw file](https://github.com/cesanta/docker_auth/blob/c700378da51f5742f8733c0a90524d27b0cefab9/auth_server/authn/mongo_auth.go#L52)):*
no need to log this

---

*[auth_server/authn/mongo_auth.go, line 63 \[r1\]](https://reviewable.io:443/reviews/cesanta/docker_auth/55#-K5NF8DN4g88TWs1ypwW:-K5NF8DN4g88TWs1ypwX:-668489614) ([raw file](https://github.com/cesanta/docker_auth/blob/c700378da51f5742f8733c0a90524d27b0cefab9/auth_server/authn/mongo_auth.go#L63)):*
question: what will be returned if collection does not exist?

(bear in mind, i'm not familiar with mongo db at all)

basically, if authenticator could not find any record associated with this user, it should return a `NoMatch` error.
this allows chaining authenticators  responsible for different sets of users.

---

*[auth_server/authn/mongo_auth.go, line 79 \[r1\]](https://reviewable.io:443/reviews/cesanta/docker_auth/55#-K5NE_vPx1OKCMboEAb3:-K5NE_vPx1OKCMboEAb4:-1489417370) ([raw file](https://github.com/cesanta/docker_auth/blob/c700378da51f5742f8733c0a90524d27b0cefab9/auth_server/authn/mongo_auth.go#L79)):*
please remove all this commented-out code

---

*[auth_server/authz/acl_mongo.go, line 98 \[r1\]](https://reviewable.io:443/reviews/cesanta/docker_auth/55#-K5NG3waRhHuJz5w4cav:-K5NG3waRhHuJz5w4caw:2066332879) ([raw file](https://github.com/cesanta/docker_auth/blob/c700378da51f5742f8733c0a90524d27b0cefab9/auth_server/authz/acl_mongo.go#L98)):*
no need to log this

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/docker_auth/55#-:-K5NGUmgXVu_zM-mwK_0:-1513782744)*

**Comment by carsonoid** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[auth_server/authn/mongo_auth.go, line 63 \[r1\]](https://reviewable.io:443/reviews/cesanta/docker_auth/55#-K5NF8DN4g88TWs1ypwW:-K5OcIrFXsEFAtNv-NzT:411337876) ([raw file](https://github.com/cesanta/docker_auth/blob/c700378da51f5742f8733c0a90524d27b0cefab9/auth_server/authn/mongo_auth.go#L63)):*
Both the "DB" and "C" calls simply return strings that reference the Database and Collection respectively. No network communication takes place until the actual "Find" call. So the error checking in place now should be enough to implement the fall-through auth you describe. I will update it to use the NoMatch error though.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/docker_auth/55)*

**Comment by rojer** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[auth_server/authn/mongo_auth.go, line 63 \[r1\]](https://reviewable.io:443/reviews/cesanta/docker_auth/55#-K5NF8DN4g88TWs1ypwW:-K5WaOukjim2vWcTqRUw:-884821573) ([raw file](https://github.com/cesanta/docker_auth/blob/c700378da51f5742f8733c0a90524d27b0cefab9/auth_server/authn/mongo_auth.go#L63)):*
can we distinguish "failure to communicate" vs "no such collection"?
because in the first case we should return error, NoMatch should only be returned if we successfully communicated to the db but found no such record.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/docker_auth/55)*

**Comment by rojer** [comment]
please squash commits

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/docker_auth/55#-:-K5WahZGVMI9Ja8u7cPW:-993290420)*

**Comment by rojer** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/reference.yml, line 75 \[r2\]](https://reviewable.io:443/reviews/cesanta/docker_auth/55#-K5WarNvA4Dff2zNK19I:-K5WarNwkY9oJC8QkSsy:1280738411) ([raw file](https://github.com/cesanta/docker_auth/blob/f5fcd5501f1ad592b41a65d76aad1fe14669e6c6/examples/reference.yml#L75)):*
should be indented to be below mongo_auth (for readability, even if not strictly necessary)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/docker_auth/55)*

**Comment by carsonoid** [comment]
Whoops! Sorry about that. I haven't used reviewable before so I didn't realize it would update you automatically when I pushed. I want to test the NoMatch fall-through and then I'll squash it all and push up the final draft.

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[auth_server/authn/mongo_auth.go, line 63 \[r1\]](https://reviewable.io:443/reviews/cesanta/docker_auth/55#-K5NF8DN4g88TWs1ypwW:-K5YJE3YcriaJHbNORUg:-795405530) ([raw file](https://github.com/cesanta/docker_auth/blob/c700378da51f5742f8733c0a90524d27b0cefab9/auth_server/authn/mongo_auth.go#L63)):*
There is a error we can catch when there are zero results. I'll make sure to return a NoMatch when we get that and the returned error otherwise.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/docker_auth/55#-:-K5YJhcjw52WLFhf2quW:863323614)*

**Comment by rojer** [comment]
last minor comment and we're go

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[auth_server/authz/acl_mongo.go, line 17 \[r3\]](https://reviewable.io:443/reviews/cesanta/docker_auth/55#-K5bP4hbnsvSptspSYF9:-K5bP4hbnsvSptspSYFA:-56674025) ([raw file](https://github.com/cesanta/docker_auth/blob/0d7d2c3a48bc3ed9cf79de0ebef70d9267c0d810/auth_server/authz/acl_mongo.go#L17)):*
Mongo is kinda redundant here, i don't expect any other kind of Config to live under mgo_session package.
so, let's drop Mongo.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/docker_auth/55#-:-K5bPMzBjQFLgJDrIwfG:1403968630)*

**Comment by rojer** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[auth_server/server/config.go, line 40 \[r4\]](https://reviewable.io:443/reviews/cesanta/docker_auth/55#-K5boJqtBFE6XTeaX8GR:-K5boJqtBFE6XTeaX8GS:-450197139) ([raw file](https://github.com/cesanta/docker_auth/blob/cd17fff5f8b4d80e597f7d260ea31cf0b7d0ccc1/auth_server/server/config.go#L40)):*
run gofmt on the whole thing, for OCD-compliance

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/docker_auth/55)*

**Comment by rojer** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[auth_server/mgo_session/mgo_session.go, line 39 \[r5\]](https://reviewable.io:443/reviews/cesanta/docker_auth/55#-K5caElCNr_q_M8fR2To:-K5caElCNr_q_M8fR2Tp:-525907849) ([raw file](https://github.com/cesanta/docker_auth/blob/3412394a0b7c4d0e03c649786933d4b74295726b/auth_server/mgo_session/mgo_session.go#L39)):*
um, sorry, didn't notice that you mix mongo authz and authn configuration in one struct.
we shouldn't do that. it's a good idea to have common session config struct between the two, but authn.MongoAuthConfig and authz.ACLMongoConfig should be separate.
nboth should contain the session config, which will basically be mgo_session.DialConfig, and their respective options (just collection for authn.MongoAuth and collection + cache ttl for acl).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/docker_auth/55)*

**Comment by rojer** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[auth_server/mgo_session/mgo_session.go, line 39 \[r5\]](https://reviewable.io:443/reviews/cesanta/docker_auth/55#-K5caElCNr_q_M8fR2To:-K5cbM7TyaG0SGAIvtNh:-1676785798) ([raw file](https://github.com/cesanta/docker_auth/blob/3412394a0b7c4d0e03c649786933d4b74295726b/auth_server/mgo_session/mgo_session.go#L39)):*
sorry, to clarify: mgo_session.DialConfig should become mgo_session.Config and should be used by authn.MongoAuthConfig and authz.ACLMongoConfig as a member.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/docker_auth/55)*

**Comment by carsonoid** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[auth_server/mgo_session/mgo_session.go, line 39 \[r5\]](https://reviewable.io:443/reviews/cesanta/docker_auth/55#-K5caElCNr_q_M8fR2To:-K5gjaLNggISTSB9KK0j:676635175) ([raw file](https://github.com/cesanta/docker_auth/blob/3412394a0b7c4d0e03c649786933d4b74295726b/auth_server/mgo_session/mgo_session.go#L39)):*
Done

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/docker_auth/55)*

**Comment by rojer** [comment]
Reviewed 4 of 9 files at r1, 1 of 3 files at r2, 1 of 2 files at r3, 4 of 4 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/docker_auth/55)*

**Comment by rojer** [comment]
thank you!

**Comment by rojer** [comment]
pushed to :latest

**Pull request merged**
