### PR TITLE
add vendor/

### PR DESCRIPTION
**Pull request by zyfdegh**
Add vendor directory. See issue #150

---
This change is [Reviewable](https://reviewable.io/reviews/cesanta/docker_auth/161)

### CODE REVIEW

**Comment by rojer** [comment]
rather than bringing in all the files as blobs, i'd rather deps be brought in as submodules.

**Comment by zyfdegh** [comment]
Well, adding `vendor/*` makes it easier for beginners who just cloned this repo to build and start docker_auth in minutes.
Especially in some areas like China, due to bad network, some packages like `gopkg.in/*` and `golang.org/*` cannot be fetched by `go get`. :-/

**Comment by rojer** [comment]
mmm... those concerns are secondary in nature. i'd rather not have additional 170K lines of code in this repo.

**Comment by zyfdegh** [comment]
OK, never mind. This issue may be closing now.

**Comment by rojer** [comment]
what did you use to identify all the dependencies? i did intend to do it, but with submodules.

**Comment by dennisdegreef** [comment]
This might be something to look at https://github.com/robfig/glock

**Comment by adamdecaf** [comment]
Fyi, there's a makefile command that downloads these. They're still pinned pretty well. See: https://github.com/cesanta/docker_auth/pull/233 

I agree that now we should use vgo or dep though.

**Comment by zyfdegh** [comment]
@rojer The `govendor` will solve the external dependencies automatically

**Comment by zyfdegh** [comment]
@adamdecaf Thank you for reminding, it's already done!

**Comment by zyfdegh** [comment]
See auth_server/Makefile and use `make deps` to sync dependencies, closing

**Pull request closed without merging**
