### PR TITLE
Teams ACLs

### PR DESCRIPTION
**Pull request by raphink**
This PR aims to implement #117

---

This change is [Reviewable](https://reviewable.io/reviews/cesanta/docker_auth/118)

### CODE REVIEW

**Comment by rojer** [comment]
while what you did here is not terrible, i'd like a more generic mechanism of passing data between authn and authz parts. "team" is too specific to GH to deserve a field in the ACL struct. we don't want to be too specific.
perhaps, i'm thinking, we can make it possible for the authn mechanism to add _labels_, with values, and then teach authz/acl.go to match them. GH authn provider will pass down "team" label, GA may pass "domain", etc.

let's finish GH authn first and then get back to this.

**Comment by raphink** [comment]
Dockerhub has [orgs and teams](https://docs.docker.com/docker-hub/orgs/), so it could be interesting to try and match that behavior maybe.

**Comment by raphink** [comment]
As a note also, these informations (Domain/Organizations/Teams/Email) usually require to use the access token (both for Google and Github). So if we use this information for authz, we must either:

* always use the token, which kind of makes the expires_in/revalidate_after parameters moot
* or store the information (in a levelDB for example) until the token expires/needs revalidation, which means there is a delay in authorization propagation when a user's email/team/org is modified in Google/GitHub

**Comment by rojer** [comment]
storing alongside ticket is fine. those who are concerned with propagation delay should be equally concerned with ticket staleness, they can reduce it.

**Comment by raphink** [comment]
OK. Considering this problem is apparently linked to OAuth authentications, how about adding these fields to the `TokenDBValue`?

**Comment by rojer** [comment]
so, i'm leaning towards generic mechanism for passing labels from authenticator (whichever authenticated the user) to authorizer. a string:string map, or maybe think ahead and use some sort of variant structure that can hold numbers for easy matching of numbers. i don't know what the situation is in Go-land, but in C++ and Qt we have QVariant - something of that sort would be ideal. but if it's too hairy, then we can start with just string values.

adding to tokendb - yeah, that'll do. how authn provider comes up with labels is really up to it, GH can store in tokendb. but again - make tokendb store generic labels. "team", "organization" and such should not leave GH authn code.
now, best syntax for matching labels in acls? ideally, as you suggested, it would be nice if labels just augmented the key space created by ticket so that we can do `match: {team: ...}` the same way as we do `match: {account: ...}`. but if it's too difficult to do, then something like `match: {account: ..., labels: {team: ...}}` is also an option.

**Comment by raphink** [comment]
OK, so maybe as you suggest a `Labels` field as a `map[string]interface{}` in `TokenDBValue`. It would need to be a map of `interface{}` as there may be lists (e.g. teams) instead of strings (e.g. email) as values.

As for ACLs, as far as I'm concerned, I'm currently mostly interested in `match: { name: "${team}/*"}` (which is what I have implemented in this PR) to implement "team namespaces", but that comes as a bundle with the rest imo.

**Comment by rojer** [comment]
not a fan of maps-to-interface{}, this should be the last resort.
my Go-fu is not that strong to begin with, and it's very late here, but please look around to somehow limit it to "either string or a list of strings" on entry.

**Comment by rojer** [comment]
by "on entry" i mean so that type of label is checked at compile time rather than at run time with a type switch.

**Comment by raphink** [comment]
Right. I'm not a Go expert either, but will try to get something strict-y.

**Comment by raphink** [comment]
Would it work if we considered that every label has a slice of string as a value, and some happen to only contain one value in the slice?

**Comment by raphink** [comment]
`${<label>}` would be replaced by the values joined with `|`.

**Comment by carsonoid** [comment]
The recent addition of label support to mongo and static auth privides for a more generic way to do this.

**Comment by techknowlogick** [comment]
Thanks for this PR :)

The codebase has evolved since this PR was made, and so I will close it. As mentioned above, I think label support would be a generic way to go about this.

**Pull request closed without merging**
