### PR TITLE
Creating token store interface.  Implementing leveldb as a token store.

### PR DESCRIPTION
**Pull request by dkjer**
Creating token store interface. Implementing leveldb as a token store.

[Review on Reviewable](https://reviewable.io/reviews/cesanta/docker_auth/29)

### CODE REVIEW

**Comment by rojer** [comment]
hi Donald

i'd like this split into two changes: first that introduces the token store interface, and a second one that implements Redis store. this may take some time to review, as i have not up to this point given a thought to the token storage.
a bit of rationale as to why leveldb is not good enough for your case would help understand the problem too.

**Comment by dkjer** [comment]
@rojer Sure, I'll work on splitting this up. 

As for why leveldb doesn't work for us, only a single process can access a particular database at a time.  We run multiple instances of the registry and auth services behind ELBs, and need shared access to the same set of tokens.

**Comment by dkjer** [comment]
@rojer PR's split up.  #29 introduces the token store (and a leveldb implementation of a token store).

https://github.com/lindenlab/docker_auth/pull/1/files is what the next PR will look like, to add redis support.

**Comment by rojer** [comment]
ok, fair enough. we'll find a way to accommodate this in in one some form,
but please give me some time to think on the interface.
i'm extremely busy with my main job at the moment...

On Thu, Sep 10, 2015 at 12:25 AM Donald Kjer <notifications@github.com>
wrote:

> @rojer <https://github.com/rojer> Sure, I'll work on splitting this up.
>
> As for why leveldb doesn't work for us, only a single process can access a
> particular database at a time. We run multiple instances of the registry
> and auth services behind ELBs, and need shared access to the same set of
> tokens.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cesanta/docker_auth/pull/29#issuecomment-139071169>.
>
-- 
Deomid Ryabkov,
Software Engineer
Cesanta Software Ltd.

**Comment by rojer** [comment]
sorry, this took longer than even i expected. the interface looks good.
i'd like to keep the package structure simpler for now, however. specifically: please remove the separate "factory" package, pull the factory method up to the `tokenstore` package and call the factory method NewTokenStore. keep the string argument. also move leveldb implementation up to the tokenstore package, call it LevelDBTokenStore.


---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[auth_server/authn/tokenstore/tokenstore.go, line 11 \[r1\]](https://reviewable.io:443/reviews/cesanta/docker_auth/29#-K0NYUzA3o9ZUUTHolTY)** ([raw file](https://github.com/cesanta/docker_auth/blob/06fe4b195b5339d37165d42d3f5aee08149eed91/auth_server/authn/tokenstore/tokenstore.go#L11)):</sup>
please document the interface methods and their goroutine safety requirements


---

<sup>**[auth_server/authn/tokenstore/tokenstore.go, line 14 \[r1\]](https://reviewable.io:443/reviews/cesanta/docker_auth/29#-K0NYHbjjruqV0Krkquv)** ([raw file](https://github.com/cesanta/docker_auth/blob/06fe4b195b5339d37165d42d3f5aee08149eed91/auth_server/authn/tokenstore/tokenstore.go#L14)):</sup>
let's call this Name(), a-la Authenticator and Authorizer


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/docker_auth/29)

**Comment by rojer** [comment]
@dkjer do you plan to finish this?

**Comment by dkjer** [comment]
@rojer Sorry, I'm no longer working on this.  Feel free to take over the PR, or close it

**Comment by rojer** [comment]
we have a TokenDB interface now, implemented as part of the GitHub authn PR.

https://github.com/cesanta/docker_auth/blob/master/auth_server/authn/tokendb.go#L38

**Pull request closed without merging**
