### PR TITLE
Docker nightlies

### LINKED ISSUE #288: Any plans for new Docker Image Release?
Any plans for a new release in Docker Hub? Last image was pushed over 7 months ago.

### PR DESCRIPTION
**Pull request by techknowlogick**
Before merging two github action secrets will need to be added:
`DOCKER_USERNAME`
`DOCKER_PASSWORD`

Whichever user is used will need to have write permissions to the docker image.

Another PR coming soon which will support git tags -> docker image tags

Fix #288

### CODE REVIEW

**Comment by gabrielcalderon** [comment]
Looking forward to this PR! 👍🏻

**Comment by rojer** [comment]
ok, i'll need to figure out which user to use...

**Comment by techknowlogick** [comment]
> ok, i'll need to figure out which user to use...

I'd recommend creating a new user on docker hub and giving it appropriate permissions to just this image so that your personal credentials don't need to be used.

**Comment by Ka0o0** [comment]
@rojer any chance you can look into this?

**Comment by rojer** [comment]
@techknowlogick how can i contact you? can you please drop me an email at rojer@rojer.me

**Comment by techknowlogick** [comment]
@rojer Ive just sent you an email with my information:)

**Pull request merged**
