### PR TITLE
Add authorization based on Github teams

### PR DESCRIPTION
**Pull request by karmi**
This pull request improves the Github _authentication_ workflow, and adds _authorization_ based on user's Github teams.

The improvements add a visually more appealing "Login with Github" page, and a full HTML page for the result page, in order to show the `docker login` instructions properly formatted.

The added `fetchTeams()` function will retrieve a list of user's Github teams _per configured organization_. It doesn't fetch any teams if an organization is not set in the YAML configuration, with the assumption that the user of the authentication server wants to use it in some kind of private Docker registry, tied to a specific organization. (Moreover, the team names are not unique across organizations, so ignoring organization would make it danegerously ambiguous. We have considered prepending the organization name to the team name, but it looked like unnecessary complication for the imagined use case). The implementation takes pagination into account, parsing the appropriate response headers.

The updated `doGitHubAuthCreateToken()` function will call the `fetchTeams()` function, and store the array of team names in the `Labels` in the token itself — therefore it relies on the https://github.com/cesanta/docker_auth/pull/217 pull request. The updated `Authenticate()` function will return the labels, instead of `nil`, as it originally did.

This pull request implements the feature request in https://github.com/cesanta/docker_auth/issues/191.

---
This change is [Reviewable](https://reviewable.io/reviews/cesanta/docker_auth/219)

### CODE REVIEW

**Comment by karmi** [comment]
Hello, can we get some feedback on this patch?

**Comment by alex-mohemian** [comment]
I would love that to be merged :) Perfect for our use-case.

**Comment by karmi** [comment]
Hi @rojer, any chance you would have a look at this as well?

**Comment by adamdecaf** [comment]
@rojer Any chance this could be reviewed and merged? Having the ability to restrict by github teams is really important to me.

**Comment by adamdecaf** [comment]
@karmi Was there something needed to get this to compile? I'm running with #217 but seeing the following error. I think it's because this project doesn't have vendor/ at the root.

```
$ make
CGO_ENABLED=0 go build -v -i --ldflags=--s
github.com/cesanta/docker_auth/auth_server/authn
# github.com/cesanta/docker_auth/auth_server/authn
authn/tokendb_gcs.go:36:83: cannot use "github.com/cesanta/docker_auth/auth_server/vendor/google.golang.org/api/option".WithServiceAccountFile(clientSecretFile) (type "github.com/cesanta/docker_auth/auth_server/vendor/google.golang.org/api/option".ClientOption) as type "google.golang.org/api/option".ClientOption in argument to "cloud.google.com/go/storage".NewClient:
	"github.com/cesanta/docker_auth/auth_server/vendor/google.golang.org/api/option".ClientOption does not implement "google.golang.org/api/option".ClientOption (wrong type for Apply method)
		have Apply(*"github.com/cesanta/docker_auth/auth_server/vendor/google.golang.org/api/internal".DialSettings)
		want Apply(*"google.golang.org/api/internal".DialSettings)
make: *** [build] Error 2

```

**Comment by rojer** [comment]
@adamdecaf my apologies, `EBUSY` as always... but looking now.

**Comment by rojer** [comment]
hey, this looks pretty good! i don't even have anything to complain about :)
sorry for keeping you waiting @karmi

**Comment by rojer** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cesanta/docker_auth/219)*

**Comment by adamdecaf** [comment]
@rojer Thanks for the merges! Could we get a pre-release build out? I'll help verify it's g2g.

**Comment by rojer** [comment]
@adamdecaf try `cesanta/docker_auth:2018060114`

**Comment by adamdecaf** [comment]
@rojer That image works. I'm able to auth against it.

**Comment by rojer** [comment]
@adamdecaf ok, tagged as `:latest`

**Comment by karmi** [comment]
@adamdecaf, doesn't ring any bells, I know we added some parts to the build mechanics, but this looks like some unrelated problem with type mismatches — maybe different versions of the third-party library?

**Comment by karmi** [comment]
@rojer, thank you :) And absolutely no worries, I know how it goes pretty well :)

**Pull request merged**
