### PR TITLE
add couchdb auth and acl support

### PR DESCRIPTION
**Pull request by zyfdegh**
I followed the auth and ACL codes according to MongoDB way. The file structure may not be suitable now. But it works well.

---
This change is [Reviewable](https://reviewable.io/reviews/cesanta/docker_auth/160)

### CODE REVIEW

**Comment by zyfdegh** [comment]
The issue is described at #156

**Comment by rojer** [comment]
sorry, it may take a while before i can get to reviewing this.

**Comment by zyfdegh** [comment]
Yea, take your time.

**Comment by techknowlogick** [comment]
Thanks for this PR :)

The codebase has evolved since this PR was made, and so I will close it. If you are open to re-submitting it and resolving the conflicts, I think it would be a benefit to the project.

**Pull request closed without merging**
