### PR TITLE
MAP LDAP account attributes to labels such as groups

### PR DESCRIPTION
**Pull request by mrueg**
Since the original PR went stale, I
* Cherry-picked the commits from https://github.com/cesanta/docker_auth/pull/167 so they apply against master again. 
* Added example ACL as requested

@rojer @alonbl Please have another look. Also @kcd83 fyi :)

---
This change is [Reviewable](https://reviewable.io/reviews/cesanta/docker_auth/228)

### CODE REVIEW

**Comment by alonbl** [comment]
Looks ok!

**Comment by mrueg** [comment]
@rojer Friendly ping :)

**Comment by jaen** [comment]
@mrueg is that perchance available somewhere in Dockerhub? Or would I have to build an image on my own?

**Comment by mrueg** [comment]
@jaen I've patched it downstream in gentoo, (sys-auth/docker_auth), that's where I'm currently using it.

**Comment by jaen** [comment]
I see, thanks for the info. I guess I'll just build my own image then.

**Comment by rojer** [comment]
@mrueg can you address @jaen 's comment? seems ok and good to go to me otherwise

**Comment by aleofreddi** [comment]
For my use case It would be really great to use a regex as well to extract the label value (besides the CN extraction). I could implement that on top of this PR, but is there any hope this one gets merged?

**Comment by abaddononion** [comment]
Just starting using the cesanta/docker_auth container, and getting this PR merged would be really helpful for my purposes, as well!

**Comment by pinepain** [comment]
@mrueg million thanks for taking care of this!

@jaen would you think that merging this one and then addressing lowercasing CN in a separate PR? Apparently, adding groups filtering has some touch on it and it seems to be this PR have a good change to stale as the original one too.

**Comment by jaen** [comment]
Ah, sure. I'm not directly involved with the project that initially required this now, so I don't have any strong feelings on having this included anymore.

**Comment by rojer** [comment]
ok, ok, people, i'm on it.
sorry for neglecting this for so long, docker_auth is far from my main LoB and LDAP is even further off.

**Comment by rojer** [comment]
ok, this is now in `:latest` and `:1.4.0`.

**Pull request merged**
