### PR TITLE
Add MongoDB backend for ACLs

### PR DESCRIPTION
**Pull request by kwk**
This adds the ability to store ACLs in a MongoDB database. There's also
a documentation file in `docs/ACL_Backend_MongoDB.md` that explains the
document layout inside a MongoDB.

See also #38 for the initial discussion on this topic.

[Review on Reviewable](https://reviewable.io/reviews/cesanta/docker_auth/43)

### CODE REVIEW

**Comment by rojer** [comment]
can you please squash the commits into one and rebase it to master (comment field change have been merged)

**Comment by kwk** [comment]
@rojer Since the commits to be squashed have already been pushed to my branch I need to create a new branch first and from there create a new pull request. I'm closing this PR in favor of the new one.

**Comment by kwk** [comment]
@rojer Please see #44 for the new pull request.

**Comment by rojer** [comment]
hm. unless i misunderstand, `push -f` would've been sufficient. but ok.

**Pull request closed without merging**
