### PR TITLE
Add support for Google authentication

### PR DESCRIPTION
**Pull request by rojer**
Notably, Google password is *not* used for Docker login.

#2

[Review on Reviewable](https://reviewable.io/reviews/cesanta/docker_auth/5)

### CODE REVIEW

**Comment by mmikulicic** [comment]
Review status: 9 of 10 files reviewed, 9 unresolved discussions, all commit checks successful.
Reviewed files:
- .gitignore @ r1
- auth_config.yml @ r1
- auth_server/main.go @ r1
- auth_server/server/config.go @ r1
- auth_server/server/server.go @ r1
- auth_server/server/static_auth.go @ r1
- examples/reference.yml @ r1
- examples/simple.yml @ r1
- README.md @ r1

---

<sup>**[auth_server/server/google_auth.go, line 41 \[r1\]](https://reviewable.io:443/reviews/cesanta/docker_auth/5#-JqtE_wQh6q3j_1I7Uva)** ([raw file](https://github.com/cesanta/docker_auth/blob/6ceb2b73fc8f96a3c69eab9b6bcdd7faf36108e0/auth_server/server/google_auth.go#L41)):</sup>
why don't you just import that package?

---

<sup>**[auth_server/server/google_auth.go, line 174 \[r1\]](https://reviewable.io:443/reviews/cesanta/docker_auth/5#-JqtMYs8-Bl-_JnUnhbl)** ([raw file](https://github.com/cesanta/docker_auth/blob/6ceb2b73fc8f96a3c69eab9b6bcdd7faf36108e0/auth_server/server/google_auth.go#L174)):</sup>
```fmt.Fprintf(...``` here as well

---

<sup>**[auth_server/server/google_auth.go, line 336 \[r1\]](https://reviewable.io:443/reviews/cesanta/docker_auth/5#-JqtLa4w0nrYMLomRMtv)** ([raw file](https://github.com/cesanta/docker_auth/blob/6ceb2b73fc8f96a3c69eab9b6bcdd7faf36108e0/auth_server/server/google_auth.go#L336)):</sup>
let's be more explicit here about the usage, e.g.:

```
Use this password on `docker login`
````

Btw, I guess it would be also important to show the user name. The user might wonder whether it's the email address and in case of multiple accounts, it's nice to show a visual confirmation of which account was actually used to signin.
In fact the email address is shown when rendering `google_auth` after initial signin.

---

<sup>**[auth_server/server/google_auth.go, line 387 \[r1\]](https://reviewable.io:443/reviews/cesanta/docker_auth/5#-JqtIHnQrJls0JsUXW3b)** ([raw file](https://github.com/cesanta/docker_auth/blob/6ceb2b73fc8f96a3c69eab9b6bcdd7faf36108e0/auth_server/server/google_auth.go#L387)):</sup>
why do we have to obtain the access token at all?

Isn't obtaining the token info via https://www.googleapis.com/oauth2/v1/tokeninfo? and checking that the clientid matches is sufficient in order to validate that the user is who it claims to be?

Do we really have to invoke google API's on behalf of the user anywhere? (the user email and user name are part of the tokeninfo)

Using only tokeninfo would also have the advantage of not requiring storing the secret key, simplifying the configuration.

---

<sup>**[auth_server/server/google_auth.go, line 519 \[r1\]](https://reviewable.io:443/reviews/cesanta/docker_auth/5#-JqtJgLGx1zx7oOCCZvj)** ([raw file](https://github.com/cesanta/docker_auth/blob/6ceb2b73fc8f96a3c69eab9b6bcdd7faf36108e0/auth_server/server/google_auth.go#L519)):</sup>
why not:

```fmt.Fprintf(rw, ...)```

---

<sup>**[auth_server/server/google_auth.go, line 530 \[r1\]](https://reviewable.io:443/reviews/cesanta/docker_auth/5#-JqtJmfHSHGZXJli6WoD)** ([raw file](https://github.com/cesanta/docker_auth/blob/6ceb2b73fc8f96a3c69eab9b6bcdd7faf36108e0/auth_server/server/google_auth.go#L530)):</sup>
I'd even do it here:

`fmt.Fprint(rw, "singed out")`

---

<sup>**[auth_server/server/server.go, line 216 \[r1\]](https://reviewable.io:443/reviews/cesanta/docker_auth/5#-JqtJw2BBqzrsh9lRAlJ)** ([raw file](https://github.com/cesanta/docker_auth/blob/6ceb2b73fc8f96a3c69eab9b6bcdd7faf36108e0/auth_server/server/server.go#L216)):</sup>
why not 

```
fmt.Fprintf(rw, "<h1>%s</h1>\n", as.config.Token.Issuer)
```

?

---

<sup>**[auth_server/server/server.go, line 218 \[r1\]](https://reviewable.io:443/reviews/cesanta/docker_auth/5#-JqtK22-Yif8baadlQOU)** ([raw file](https://github.com/cesanta/docker_auth/blob/6ceb2b73fc8f96a3c69eab9b6bcdd7faf36108e0/auth_server/server/server.go#L218)):</sup>
I'd even do it here

---

<sup>**[auth_server/server/server.go, line 253 \[r1\]](https://reviewable.io:443/reviews/cesanta/docker_auth/5#-JqtK8buGyjUdxTfDpn5)** ([raw file](https://github.com/cesanta/docker_auth/blob/6ceb2b73fc8f96a3c69eab9b6bcdd7faf36108e0/auth_server/server/server.go#L253)):</sup>
isn't `result` already a `[]byte` ?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/docker_auth/5)

**Comment by rojer** [comment]
Review status: 8 of 10 files reviewed, 9 unresolved discussions, all commit checks successful.

---

<sup>**[auth_server/server/google_auth.go, line 41 \[r1\]](https://reviewable.io:443/reviews/cesanta/docker_auth/5#-JqtE_wQh6q3j_1I7Uva)** ([raw file](https://github.com/cesanta/docker_auth/blob/6ceb2b73fc8f96a3c69eab9b6bcdd7faf36108e0/auth_server/server/google_auth.go#L41)):</sup>
it's a big package that at the moment does not actually provide much of anything. i'm all for transitioning to it when it actually supports validating tokens, but for now i think a little copy-paste is fine.

---

<sup>**[auth_server/server/google_auth.go, line 174 \[r1\]](https://reviewable.io:443/reviews/cesanta/docker_auth/5#-JqtMYs8-Bl-_JnUnhbl)** ([raw file](https://github.com/cesanta/docker_auth/blob/6ceb2b73fc8f96a3c69eab9b6bcdd7faf36108e0/auth_server/server/google_auth.go#L174)):</sup>
ah, nice. thanks! i did check Writer api for some printf-like function , didn't find any and was not aware of the fmt.Fprint{,f}

---

<sup>**[auth_server/server/google_auth.go, line 336 \[r1\]](https://reviewable.io:443/reviews/cesanta/docker_auth/5#-JqtLa4w0nrYMLomRMtv)** ([raw file](https://github.com/cesanta/docker_auth/blob/6ceb2b73fc8f96a3c69eab9b6bcdd7faf36108e0/auth_server/server/google_auth.go#L336)):</sup>
Done.

---

<sup>**[auth_server/server/google_auth.go, line 387 \[r1\]](https://reviewable.io:443/reviews/cesanta/docker_auth/5#-JqtIHnQrJls0JsUXW3b)** ([raw file](https://github.com/cesanta/docker_auth/blob/6ceb2b73fc8f96a3c69eab9b6bcdd7faf36108e0/auth_server/server/google_auth.go#L387)):</sup>
the token we get from web is short-lived, usually an hour. we have to be able to refresh the token to be able to continue to verify that user's account is valid. we only do profile lookup on user's behalf, and then only to validate the access token to verify that their google account is still valid (e.g. not terminated and access to docker repository has not been revoked).

---

<sup>**[auth_server/server/google_auth.go, line 519 \[r1\]](https://reviewable.io:443/reviews/cesanta/docker_auth/5#-JqtJgLGx1zx7oOCCZvj)** ([raw file](https://github.com/cesanta/docker_auth/blob/6ceb2b73fc8f96a3c69eab9b6bcdd7faf36108e0/auth_server/server/google_auth.go#L519)):</sup>
Done.

---

<sup>**[auth_server/server/google_auth.go, line 530 \[r1\]](https://reviewable.io:443/reviews/cesanta/docker_auth/5#-JqtJmfHSHGZXJli6WoD)** ([raw file](https://github.com/cesanta/docker_auth/blob/6ceb2b73fc8f96a3c69eab9b6bcdd7faf36108e0/auth_server/server/google_auth.go#L530)):</sup>
Done.

---

<sup>**[auth_server/server/server.go, line 216 \[r1\]](https://reviewable.io:443/reviews/cesanta/docker_auth/5#-JqtJw2BBqzrsh9lRAlJ)** ([raw file](https://github.com/cesanta/docker_auth/blob/6ceb2b73fc8f96a3c69eab9b6bcdd7faf36108e0/auth_server/server/server.go#L216)):</sup>
Done.

---

<sup>**[auth_server/server/server.go, line 218 \[r1\]](https://reviewable.io:443/reviews/cesanta/docker_auth/5#-JqtK22-Yif8baadlQOU)** ([raw file](https://github.com/cesanta/docker_auth/blob/6ceb2b73fc8f96a3c69eab9b6bcdd7faf36108e0/auth_server/server/server.go#L218)):</sup>
Done.

---

<sup>**[auth_server/server/server.go, line 253 \[r1\]](https://reviewable.io:443/reviews/cesanta/docker_auth/5#-JqtK8buGyjUdxTfDpn5)** ([raw file](https://github.com/cesanta/docker_auth/blob/6ceb2b73fc8f96a3c69eab9b6bcdd7faf36108e0/auth_server/server/server.go#L253)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/docker_auth/5)

**Comment by mmikulicic** [comment]
Review status: all files reviewed, 3 unresolved discussions, all commit checks successful.
Reviewed files:
- .gitignore @ r1
- auth_config.yml @ r1
- auth_server/main.go @ r1
- auth_server/Makefile @ r3
- auth_server/server/config.go @ r1
- auth_server/server/google_auth.go @ r3
- auth_server/server/server.go @ r2
- auth_server/server/static_auth.go @ r1
- examples/reference.yml @ r1
- examples/simple.yml @ r1
- README.md @ r1

---

<sup>**[auth_server/server/google_auth.go, line 41 \[r1\]](https://reviewable.io:443/reviews/cesanta/docker_auth/5#-JqtE_wQh6q3j_1I7Uva)** ([raw file](https://github.com/cesanta/docker_auth/blob/6ceb2b73fc8f96a3c69eab9b6bcdd7faf36108e0/auth_server/server/google_auth.go#L41)):</sup>
don't have strong opinion on it, but for the OurCI project I made the choice of actually reusing existing structures. This package basically has the Go structures generated from a JSON "schema" that defines the API. Nothing more authoritative than that.

---

<sup>**[auth_server/server/google_auth.go, line 174 \[r1\]](https://reviewable.io:443/reviews/cesanta/docker_auth/5#-JqtMYs8-Bl-_JnUnhbl)** ([raw file](https://github.com/cesanta/docker_auth/blob/6ceb2b73fc8f96a3c69eab9b6bcdd7faf36108e0/auth_server/server/google_auth.go#L174)):</sup>
yep, given the lack of abstract classes, the interfaces are designed to have only a minimal number of methods

---

<sup>**[auth_server/server/google_auth.go, line 387 \[r1\]](https://reviewable.io:443/reviews/cesanta/docker_auth/5#-JqtIHnQrJls0JsUXW3b)** ([raw file](https://github.com/cesanta/docker_auth/blob/6ceb2b73fc8f96a3c69eab9b6bcdd7faf36108e0/auth_server/server/google_auth.go#L387)):</sup>
sgtm

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/docker_auth/5)

**Comment by mmikulicic** [comment]
LGTM, +@rojer 

---

Review status: all files reviewed, 3 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/docker_auth/5)

**Pull request merged**
